apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke-dev
  labels:
    app: gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
        - name: python-app-dev
          image: gcr.io/kodekloud-project-384420/gcpdevops-dev:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-gke-service
  namespace: dev
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  type: LoadBalancer
  selector:
    app: gcp
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
